# Generated by Django 3.2.6 on 2021-09-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210922_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
    ]
