# Generated by Django 3.2.6 on 2021-09-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
